loglevel = "trace"
vpn_mode = "general"
killswitch_enabled = false
killswitch_allow_ports = []
post_quantum_group_enabled = true
exclusions = []
dns_upstreams = []

[endpoint]
hostname = "vpn.example.com"
addresses = ["127.0.0.1:9443"]
custom_sni = ""
has_ipv6 = true
username = "u1"
password = "p1"
client_random = ""
skip_verification = false
certificate = """
-----BEGIN CERTIFICATE-----
REPLACE_WITH_YOUR_TRUSTED_SERVER_CERTIFICATE
-----END CERTIFICATE-----
"""
upstream_protocol = "http3"
anti_dpi = false

[listener.tun]
bound_if = "eth0"
netns = "tun"
included_routes = [
    "0.0.0.0/0",
    "2000::/3",
]
excluded_routes = [
    "0.0.0.0/8",
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "224.0.0.0/3",
]
mtu_size = 1280
