// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proxy/trusttunnel/config.proto

package trusttunnel

import (
	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransportProtocol int32

const (
	TransportProtocol_HTTP2 TransportProtocol = 0
	TransportProtocol_HTTP3 TransportProtocol = 1
	TransportProtocol_AUTO  TransportProtocol = 2
)

// Enum value maps for TransportProtocol.
var (
	TransportProtocol_name = map[int32]string{
		0: "HTTP2",
		1: "HTTP3",
		2: "AUTO",
	}
	TransportProtocol_value = map[string]int32{
		"HTTP2": 0,
		"HTTP3": 1,
		"AUTO":  2,
	}
)

func (x TransportProtocol) Enum() *TransportProtocol {
	p := new(TransportProtocol)
	*p = x
	return p
}

func (x TransportProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_trusttunnel_config_proto_enumTypes[0].Descriptor()
}

func (TransportProtocol) Type() protoreflect.EnumType {
	return &file_proxy_trusttunnel_config_proto_enumTypes[0]
}

func (x TransportProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportProtocol.Descriptor instead.
func (TransportProtocol) EnumDescriptor() ([]byte, []int) {
	return file_proxy_trusttunnel_config_proto_rawDescGZIP(), []int{0}
}

type PostQuantumGroupSetting int32

const (
	PostQuantumGroupSetting_POST_QUANTUM_GROUP_SETTING_AUTO     PostQuantumGroupSetting = 0
	PostQuantumGroupSetting_POST_QUANTUM_GROUP_SETTING_DISABLED PostQuantumGroupSetting = 1
	PostQuantumGroupSetting_POST_QUANTUM_GROUP_SETTING_ENABLED  PostQuantumGroupSetting = 2
)

// Enum value maps for PostQuantumGroupSetting.
var (
	PostQuantumGroupSetting_name = map[int32]string{
		0: "POST_QUANTUM_GROUP_SETTING_AUTO",
		1: "POST_QUANTUM_GROUP_SETTING_DISABLED",
		2: "POST_QUANTUM_GROUP_SETTING_ENABLED",
	}
	PostQuantumGroupSetting_value = map[string]int32{
		"POST_QUANTUM_GROUP_SETTING_AUTO":     0,
		"POST_QUANTUM_GROUP_SETTING_DISABLED": 1,
		"POST_QUANTUM_GROUP_SETTING_ENABLED":  2,
	}
)

func (x PostQuantumGroupSetting) Enum() *PostQuantumGroupSetting {
	p := new(PostQuantumGroupSetting)
	*p = x
	return p
}

func (x PostQuantumGroupSetting) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostQuantumGroupSetting) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_trusttunnel_config_proto_enumTypes[1].Descriptor()
}

func (PostQuantumGroupSetting) Type() protoreflect.EnumType {
	return &file_proxy_trusttunnel_config_proto_enumTypes[1]
}

func (x PostQuantumGroupSetting) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostQuantumGroupSetting.Descriptor instead.
func (PostQuantumGroupSetting) EnumDescriptor() ([]byte, []int) {
	return file_proxy_trusttunnel_config_proto_rawDescGZIP(), []int{1}
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	MaxHttp2Conns uint32                 `protobuf:"varint,3,opt,name=max_http2_conns,json=maxHttp2Conns,proto3" json:"max_http2_conns,omitempty"`
	MaxHttp3Conns uint32                 `protobuf:"varint,4,opt,name=max_http3_conns,json=maxHttp3Conns,proto3" json:"max_http3_conns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_trusttunnel_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Account) GetMaxHttp2Conns() uint32 {
	if x != nil {
		return x.MaxHttp2Conns
	}
	return 0
}

func (x *Account) GetMaxHttp3Conns() uint32 {
	if x != nil {
		return x.MaxHttp3Conns
	}
	return 0
}

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	ClientRandom  string                 `protobuf:"bytes,2,opt,name=client_random,json=clientRandom,proto3" json:"client_random,omitempty"`
	Allow         bool                   `protobuf:"varint,3,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_proxy_trusttunnel_config_proto_rawDescGZIP(), []int{1}
}

func (x *Rule) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *Rule) GetClientRandom() string {
	if x != nil {
		return x.ClientRandom
	}
	return ""
}

func (x *Rule) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

type ServerHost struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hostname        string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CertificatePath string                 `protobuf:"bytes,2,opt,name=certificate_path,json=certificatePath,proto3" json:"certificate_path,omitempty"`
	KeyPath         string                 `protobuf:"bytes,3,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerHost) Reset() {
	*x = ServerHost{}
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHost) ProtoMessage() {}

func (x *ServerHost) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHost.ProtoReflect.Descriptor instead.
func (*ServerHost) Descriptor() ([]byte, []int) {
	return file_proxy_trusttunnel_config_proto_rawDescGZIP(), []int{2}
}

func (x *ServerHost) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ServerHost) GetCertificatePath() string {
	if x != nil {
		return x.CertificatePath
	}
	return ""
}

func (x *ServerHost) GetKeyPath() string {
	if x != nil {
		return x.KeyPath
	}
	return ""
}

type ClientConfig struct {
	state                   protoimpl.MessageState     `protogen:"open.v1"`
	Server                  *protocol.ServerEndpoint   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Hostname                string                     `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Transport               TransportProtocol          `protobuf:"varint,3,opt,name=transport,proto3,enum=xray.proxy.trusttunnel.TransportProtocol" json:"transport,omitempty"`
	HasIpv6                 bool                       `protobuf:"varint,4,opt,name=has_ipv6,json=hasIpv6,proto3" json:"has_ipv6,omitempty"`
	SkipVerification        bool                       `protobuf:"varint,5,opt,name=skip_verification,json=skipVerification,proto3" json:"skip_verification,omitempty"`
	CertificatePem          string                     `protobuf:"bytes,6,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	ClientRandom            string                     `protobuf:"bytes,7,opt,name=client_random,json=clientRandom,proto3" json:"client_random,omitempty"`
	AntiDpi                 bool                       `protobuf:"varint,8,opt,name=anti_dpi,json=antiDpi,proto3" json:"anti_dpi,omitempty"`
	EnableUdp               bool                       `protobuf:"varint,9,opt,name=enable_udp,json=enableUdp,proto3" json:"enable_udp,omitempty"`
	PostQuantumGroupEnabled PostQuantumGroupSetting    `protobuf:"varint,10,opt,name=post_quantum_group_enabled,json=postQuantumGroupEnabled,proto3,enum=xray.proxy.trusttunnel.PostQuantumGroupSetting" json:"post_quantum_group_enabled,omitempty"`
	Servers                 []*protocol.ServerEndpoint `protobuf:"bytes,11,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_proxy_trusttunnel_config_proto_rawDescGZIP(), []int{3}
}

func (x *ClientConfig) GetServer() *protocol.ServerEndpoint {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ClientConfig) GetServers() []*protocol.ServerEndpoint {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ClientConfig) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ClientConfig) GetTransport() TransportProtocol {
	if x != nil {
		return x.Transport
	}
	return TransportProtocol_HTTP2
}

func (x *ClientConfig) GetHasIpv6() bool {
	if x != nil {
		return x.HasIpv6
	}
	return false
}

func (x *ClientConfig) GetSkipVerification() bool {
	if x != nil {
		return x.SkipVerification
	}
	return false
}

func (x *ClientConfig) GetCertificatePem() string {
	if x != nil {
		return x.CertificatePem
	}
	return ""
}

func (x *ClientConfig) GetClientRandom() string {
	if x != nil {
		return x.ClientRandom
	}
	return ""
}

func (x *ClientConfig) GetAntiDpi() bool {
	if x != nil {
		return x.AntiDpi
	}
	return false
}

func (x *ClientConfig) GetEnableUdp() bool {
	if x != nil {
		return x.EnableUdp
	}
	return false
}

func (x *ClientConfig) GetPostQuantumGroupEnabled() PostQuantumGroupSetting {
	if x != nil {
		return x.PostQuantumGroupEnabled
	}
	return PostQuantumGroupSetting_POST_QUANTUM_GROUP_SETTING_AUTO
}

type ServerConfig struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	Users                              []*protocol.User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Hosts                              []*ServerHost          `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Transports                         []TransportProtocol    `protobuf:"varint,3,rep,packed,name=transports,proto3,enum=xray.proxy.trusttunnel.TransportProtocol" json:"transports,omitempty"`
	Rules                              []*Rule                `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	Ipv6Available                      bool                   `protobuf:"varint,5,opt,name=ipv6_available,json=ipv6Available,proto3" json:"ipv6_available,omitempty"`
	AuthFailureStatusCode              uint32                 `protobuf:"varint,6,opt,name=auth_failure_status_code,json=authFailureStatusCode,proto3" json:"auth_failure_status_code,omitempty"`
	EnableUdp                          bool                   `protobuf:"varint,7,opt,name=enable_udp,json=enableUdp,proto3" json:"enable_udp,omitempty"`
	IcmpInterfaceName                  string                 `protobuf:"bytes,8,opt,name=icmp_interface_name,json=icmpInterfaceName,proto3" json:"icmp_interface_name,omitempty"`
	IcmpRequestTimeoutSecs             uint32                 `protobuf:"varint,9,opt,name=icmp_request_timeout_secs,json=icmpRequestTimeoutSecs,proto3" json:"icmp_request_timeout_secs,omitempty"`
	AllowPrivateNetworkConnections     bool                   `protobuf:"varint,10,opt,name=allow_private_network_connections,json=allowPrivateNetworkConnections,proto3" json:"allow_private_network_connections,omitempty"`
	IcmpRecvMessageQueueCapacity       uint32                 `protobuf:"varint,11,opt,name=icmp_recv_message_queue_capacity,json=icmpRecvMessageQueueCapacity,proto3" json:"icmp_recv_message_queue_capacity,omitempty"`
	TlsHandshakeTimeoutSecs            uint32                 `protobuf:"varint,12,opt,name=tls_handshake_timeout_secs,json=tlsHandshakeTimeoutSecs,proto3" json:"tls_handshake_timeout_secs,omitempty"`
	ClientListenerTimeoutSecs          uint32                 `protobuf:"varint,13,opt,name=client_listener_timeout_secs,json=clientListenerTimeoutSecs,proto3" json:"client_listener_timeout_secs,omitempty"`
	ConnectionEstablishmentTimeoutSecs uint32                 `protobuf:"varint,14,opt,name=connection_establishment_timeout_secs,json=connectionEstablishmentTimeoutSecs,proto3" json:"connection_establishment_timeout_secs,omitempty"`
	TcpConnectionsTimeoutSecs          uint32                 `protobuf:"varint,15,opt,name=tcp_connections_timeout_secs,json=tcpConnectionsTimeoutSecs,proto3" json:"tcp_connections_timeout_secs,omitempty"`
	UdpConnectionsTimeoutSecs          uint32                 `protobuf:"varint,16,opt,name=udp_connections_timeout_secs,json=udpConnectionsTimeoutSecs,proto3" json:"udp_connections_timeout_secs,omitempty"`
	DefaultMaxHttp2ConnsPerClient      uint32                 `protobuf:"varint,17,opt,name=default_max_http2_conns_per_client,json=defaultMaxHttp2ConnsPerClient,proto3" json:"default_max_http2_conns_per_client,omitempty"`
	DefaultMaxHttp3ConnsPerClient      uint32                 `protobuf:"varint,18,opt,name=default_max_http3_conns_per_client,json=defaultMaxHttp3ConnsPerClient,proto3" json:"default_max_http3_conns_per_client,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_trusttunnel_config_proto_rawDescGZIP(), []int{4}
}

func (x *ServerConfig) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ServerConfig) GetHosts() []*ServerHost {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *ServerConfig) GetTransports() []TransportProtocol {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *ServerConfig) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ServerConfig) GetIpv6Available() bool {
	if x != nil {
		return x.Ipv6Available
	}
	return false
}

func (x *ServerConfig) GetAuthFailureStatusCode() uint32 {
	if x != nil {
		return x.AuthFailureStatusCode
	}
	return 0
}

func (x *ServerConfig) GetEnableUdp() bool {
	if x != nil {
		return x.EnableUdp
	}
	return false
}

func (x *ServerConfig) GetIcmpInterfaceName() string {
	if x != nil {
		return x.IcmpInterfaceName
	}
	return ""
}

func (x *ServerConfig) GetIcmpRequestTimeoutSecs() uint32 {
	if x != nil {
		return x.IcmpRequestTimeoutSecs
	}
	return 0
}

func (x *ServerConfig) GetAllowPrivateNetworkConnections() bool {
	if x != nil {
		return x.AllowPrivateNetworkConnections
	}
	return false
}

func (x *ServerConfig) GetIcmpRecvMessageQueueCapacity() uint32 {
	if x != nil {
		return x.IcmpRecvMessageQueueCapacity
	}
	return 0
}

func (x *ServerConfig) GetTlsHandshakeTimeoutSecs() uint32 {
	if x != nil {
		return x.TlsHandshakeTimeoutSecs
	}
	return 0
}

func (x *ServerConfig) GetClientListenerTimeoutSecs() uint32 {
	if x != nil {
		return x.ClientListenerTimeoutSecs
	}
	return 0
}

func (x *ServerConfig) GetConnectionEstablishmentTimeoutSecs() uint32 {
	if x != nil {
		return x.ConnectionEstablishmentTimeoutSecs
	}
	return 0
}

func (x *ServerConfig) GetTcpConnectionsTimeoutSecs() uint32 {
	if x != nil {
		return x.TcpConnectionsTimeoutSecs
	}
	return 0
}

func (x *ServerConfig) GetUdpConnectionsTimeoutSecs() uint32 {
	if x != nil {
		return x.UdpConnectionsTimeoutSecs
	}
	return 0
}

func (x *ServerConfig) GetDefaultMaxHttp2ConnsPerClient() uint32 {
	if x != nil {
		return x.DefaultMaxHttp2ConnsPerClient
	}
	return 0
}

func (x *ServerConfig) GetDefaultMaxHttp3ConnsPerClient() uint32 {
	if x != nil {
		return x.DefaultMaxHttp3ConnsPerClient
	}
	return 0
}

var File_proxy_trusttunnel_config_proto protoreflect.FileDescriptor

const file_proxy_trusttunnel_config_proto_rawDesc = "" +
	"\x0a\x1e\x70\x72\x6f\x78\x79\x2f\x74\x72\x75\x73\x74\x74\x75\x6e" +
	"\x6e\x65\x6c\x2f\x63\x6f\x6e\x66\x69\x67\x2e\x70\x72\x6f\x74\x6f" +
	"\x12\x16\x78\x72\x61\x79\x2e\x70\x72\x6f\x78\x79\x2e\x74\x72\x75" +
	"\x73\x74\x74\x75\x6e\x6e\x65\x6c\x1a\x1a\x63\x6f\x6d\x6d\x6f\x6e" +
	"\x2f\x70\x72\x6f\x74\x6f\x63\x6f\x6c\x2f\x75\x73\x65\x72\x2e\x70" +
	"\x72\x6f\x74\x6f\x1a\x21\x63\x6f\x6d\x6d\x6f\x6e\x2f\x70\x72\x6f" +
	"\x74\x6f\x63\x6f\x6c\x2f\x73\x65\x72\x76\x65\x72\x5f\x73\x70\x65" +
	"\x63\x2e\x70\x72\x6f\x74\x6f\x22\x91\x01\x0a\x07\x41\x63\x63\x6f" +
	"\x75\x6e\x74\x12\x1a\x0a\x08\x75\x73\x65\x72\x6e\x61\x6d\x65\x18" +
	"\x01\x20\x01\x28\x09\x52\x08\x75\x73\x65\x72\x6e\x61\x6d\x65\x12" +
	"\x1a\x0a\x08\x70\x61\x73\x73\x77\x6f\x72\x64\x18\x02\x20\x01\x28" +
	"\x09\x52\x08\x70\x61\x73\x73\x77\x6f\x72\x64\x12\x26\x0a\x0f\x6d" +
	"\x61\x78\x5f\x68\x74\x74\x70\x32\x5f\x63\x6f\x6e\x6e\x73\x18\x03" +
	"\x20\x01\x28\x0d\x52\x0d\x6d\x61\x78\x48\x74\x74\x70\x32\x43\x6f" +
	"\x6e\x6e\x73\x12\x26\x0a\x0f\x6d\x61\x78\x5f\x68\x74\x74\x70\x33" +
	"\x5f\x63\x6f\x6e\x6e\x73\x18\x04\x20\x01\x28\x0d\x52\x0d\x6d\x61" +
	"\x78\x48\x74\x74\x70\x33\x43\x6f\x6e\x6e\x73\x22\x55\x0a\x04\x52" +
	"\x75\x6c\x65\x12\x12\x0a\x04\x63\x69\x64\x72\x18\x01\x20\x01\x28" +
	"\x09\x52\x04\x63\x69\x64\x72\x12\x23\x0a\x0d\x63\x6c\x69\x65\x6e" +
	"\x74\x5f\x72\x61\x6e\x64\x6f\x6d\x18\x02\x20\x01\x28\x09\x52\x0c" +
	"\x63\x6c\x69\x65\x6e\x74\x52\x61\x6e\x64\x6f\x6d\x12\x14\x0a\x05" +
	"\x61\x6c\x6c\x6f\x77\x18\x03\x20\x01\x28\x08\x52\x05\x61\x6c\x6c" +
	"\x6f\x77\x22\x6e\x0a\x0a\x53\x65\x72\x76\x65\x72\x48\x6f\x73\x74" +
	"\x12\x1a\x0a\x08\x68\x6f\x73\x74\x6e\x61\x6d\x65\x18\x01\x20\x01" +
	"\x28\x09\x52\x08\x68\x6f\x73\x74\x6e\x61\x6d\x65\x12\x29\x0a\x10" +
	"\x63\x65\x72\x74\x69\x66\x69\x63\x61\x74\x65\x5f\x70\x61\x74\x68" +
	"\x18\x02\x20\x01\x28\x09\x52\x0f\x63\x65\x72\x74\x69\x66\x69\x63" +
	"\x61\x74\x65\x50\x61\x74\x68\x12\x19\x0a\x08\x6b\x65\x79\x5f\x70" +
	"\x61\x74\x68\x18\x03\x20\x01\x28\x09\x52\x07\x6b\x65\x79\x50\x61" +
	"\x74\x68\x22\xaf\x04\x0a\x0c\x43\x6c\x69\x65\x6e\x74\x43\x6f\x6e" +
	"\x66\x69\x67\x12\x3c\x0a\x06\x73\x65\x72\x76\x65\x72\x18\x01\x20" +
	"\x01\x28\x0b\x32\x24\x2e\x78\x72\x61\x79\x2e\x63\x6f\x6d\x6d\x6f" +
	"\x6e\x2e\x70\x72\x6f\x74\x6f\x63\x6f\x6c\x2e\x53\x65\x72\x76\x65" +
	"\x72\x45\x6e\x64\x70\x6f\x69\x6e\x74\x52\x06\x73\x65\x72\x76\x65" +
	"\x72\x12\x1a\x0a\x08\x68\x6f\x73\x74\x6e\x61\x6d\x65\x18\x02\x20" +
	"\x01\x28\x09\x52\x08\x68\x6f\x73\x74\x6e\x61\x6d\x65\x12\x47\x0a" +
	"\x09\x74\x72\x61\x6e\x73\x70\x6f\x72\x74\x18\x03\x20\x01\x28\x0e" +
	"\x32\x29\x2e\x78\x72\x61\x79\x2e\x70\x72\x6f\x78\x79\x2e\x74\x72" +
	"\x75\x73\x74\x74\x75\x6e\x6e\x65\x6c\x2e\x54\x72\x61\x6e\x73\x70" +
	"\x6f\x72\x74\x50\x72\x6f\x74\x6f\x63\x6f\x6c\x52\x09\x74\x72\x61" +
	"\x6e\x73\x70\x6f\x72\x74\x12\x19\x0a\x08\x68\x61\x73\x5f\x69\x70" +
	"\x76\x36\x18\x04\x20\x01\x28\x08\x52\x07\x68\x61\x73\x49\x70\x76" +
	"\x36\x12\x2b\x0a\x11\x73\x6b\x69\x70\x5f\x76\x65\x72\x69\x66\x69" +
	"\x63\x61\x74\x69\x6f\x6e\x18\x05\x20\x01\x28\x08\x52\x10\x73\x6b" +
	"\x69\x70\x56\x65\x72\x69\x66\x69\x63\x61\x74\x69\x6f\x6e\x12\x27" +
	"\x0a\x0f\x63\x65\x72\x74\x69\x66\x69\x63\x61\x74\x65\x5f\x70\x65" +
	"\x6d\x18\x06\x20\x01\x28\x09\x52\x0e\x63\x65\x72\x74\x69\x66\x69" +
	"\x63\x61\x74\x65\x50\x65\x6d\x12\x23\x0a\x0d\x63\x6c\x69\x65\x6e" +
	"\x74\x5f\x72\x61\x6e\x64\x6f\x6d\x18\x07\x20\x01\x28\x09\x52\x0c" +
	"\x63\x6c\x69\x65\x6e\x74\x52\x61\x6e\x64\x6f\x6d\x12\x19\x0a\x08" +
	"\x61\x6e\x74\x69\x5f\x64\x70\x69\x18\x08\x20\x01\x28\x08\x52\x07" +
	"\x61\x6e\x74\x69\x44\x70\x69\x12\x1d\x0a\x0a\x65\x6e\x61\x62\x6c" +
	"\x65\x5f\x75\x64\x70\x18\x09\x20\x01\x28\x08\x52\x09\x65\x6e\x61" +
	"\x62\x6c\x65\x55\x64\x70\x12\x6c\x0a\x1a\x70\x6f\x73\x74\x5f\x71" +
	"\x75\x61\x6e\x74\x75\x6d\x5f\x67\x72\x6f\x75\x70\x5f\x65\x6e\x61" +
	"\x62\x6c\x65\x64\x18\x0a\x20\x01\x28\x0e\x32\x2f\x2e\x78\x72\x61" +
	"\x79\x2e\x70\x72\x6f\x78\x79\x2e\x74\x72\x75\x73\x74\x74\x75\x6e" +
	"\x6e\x65\x6c\x2e\x50\x6f\x73\x74\x51\x75\x61\x6e\x74\x75\x6d\x47" +
	"\x72\x6f\x75\x70\x53\x65\x74\x74\x69\x6e\x67\x52\x17\x70\x6f\x73" +
	"\x74\x51\x75\x61\x6e\x74\x75\x6d\x47\x72\x6f\x75\x70\x45\x6e\x61" +
	"\x62\x6c\x65\x64\x12\x3e\x0a\x07\x73\x65\x72\x76\x65\x72\x73\x18" +
	"\x0b\x20\x03\x28\x0b\x32\x24\x2e\x78\x72\x61\x79\x2e\x63\x6f\x6d" +
	"\x6d\x6f\x6e\x2e\x70\x72\x6f\x74\x6f\x63\x6f\x6c\x2e\x53\x65\x72" +
	"\x76\x65\x72\x45\x6e\x64\x70\x6f\x69\x6e\x74\x52\x07\x73\x65\x72" +
	"\x76\x65\x72\x73\x22\xdf\x08\x0a\x0c\x53\x65\x72\x76\x65\x72\x43" +
	"\x6f\x6e\x66\x69\x67\x12\x30\x0a\x05\x75\x73\x65\x72\x73\x18\x01" +
	"\x20\x03\x28\x0b\x32\x1a\x2e\x78\x72\x61\x79\x2e\x63\x6f\x6d\x6d" +
	"\x6f\x6e\x2e\x70\x72\x6f\x74\x6f\x63\x6f\x6c\x2e\x55\x73\x65\x72" +
	"\x52\x05\x75\x73\x65\x72\x73\x12\x38\x0a\x05\x68\x6f\x73\x74\x73" +
	"\x18\x02\x20\x03\x28\x0b\x32\x22\x2e\x78\x72\x61\x79\x2e\x70\x72" +
	"\x6f\x78\x79\x2e\x74\x72\x75\x73\x74\x74\x75\x6e\x6e\x65\x6c\x2e" +
	"\x53\x65\x72\x76\x65\x72\x48\x6f\x73\x74\x52\x05\x68\x6f\x73\x74" +
	"\x73\x12\x49\x0a\x0a\x74\x72\x61\x6e\x73\x70\x6f\x72\x74\x73\x18" +
	"\x03\x20\x03\x28\x0e\x32\x29\x2e\x78\x72\x61\x79\x2e\x70\x72\x6f" +
	"\x78\x79\x2e\x74\x72\x75\x73\x74\x74\x75\x6e\x6e\x65\x6c\x2e\x54" +
	"\x72\x61\x6e\x73\x70\x6f\x72\x74\x50\x72\x6f\x74\x6f\x63\x6f\x6c" +
	"\x52\x0a\x74\x72\x61\x6e\x73\x70\x6f\x72\x74\x73\x12\x32\x0a\x05" +
	"\x72\x75\x6c\x65\x73\x18\x04\x20\x03\x28\x0b\x32\x1c\x2e\x78\x72" +
	"\x61\x79\x2e\x70\x72\x6f\x78\x79\x2e\x74\x72\x75\x73\x74\x74\x75" +
	"\x6e\x6e\x65\x6c\x2e\x52\x75\x6c\x65\x52\x05\x72\x75\x6c\x65\x73" +
	"\x12\x25\x0a\x0e\x69\x70\x76\x36\x5f\x61\x76\x61\x69\x6c\x61\x62" +
	"\x6c\x65\x18\x05\x20\x01\x28\x08\x52\x0d\x69\x70\x76\x36\x41\x76" +
	"\x61\x69\x6c\x61\x62\x6c\x65\x12\x37\x0a\x18\x61\x75\x74\x68\x5f" +
	"\x66\x61\x69\x6c\x75\x72\x65\x5f\x73\x74\x61\x74\x75\x73\x5f\x63" +
	"\x6f\x64\x65\x18\x06\x20\x01\x28\x0d\x52\x15\x61\x75\x74\x68\x46" +
	"\x61\x69\x6c\x75\x72\x65\x53\x74\x61\x74\x75\x73\x43\x6f\x64\x65" +
	"\x12\x1d\x0a\x0a\x65\x6e\x61\x62\x6c\x65\x5f\x75\x64\x70\x18\x07" +
	"\x20\x01\x28\x08\x52\x09\x65\x6e\x61\x62\x6c\x65\x55\x64\x70\x12" +
	"\x2e\x0a\x13\x69\x63\x6d\x70\x5f\x69\x6e\x74\x65\x72\x66\x61\x63" +
	"\x65\x5f\x6e\x61\x6d\x65\x18\x08\x20\x01\x28\x09\x52\x11\x69\x63" +
	"\x6d\x70\x49\x6e\x74\x65\x72\x66\x61\x63\x65\x4e\x61\x6d\x65\x12" +
	"\x39\x0a\x19\x69\x63\x6d\x70\x5f\x72\x65\x71\x75\x65\x73\x74\x5f" +
	"\x74\x69\x6d\x65\x6f\x75\x74\x5f\x73\x65\x63\x73\x18\x09\x20\x01" +
	"\x28\x0d\x52\x16\x69\x63\x6d\x70\x52\x65\x71\x75\x65\x73\x74\x54" +
	"\x69\x6d\x65\x6f\x75\x74\x53\x65\x63\x73\x12\x49\x0a\x21\x61\x6c" +
	"\x6c\x6f\x77\x5f\x70\x72\x69\x76\x61\x74\x65\x5f\x6e\x65\x74\x77" +
	"\x6f\x72\x6b\x5f\x63\x6f\x6e\x6e\x65\x63\x74\x69\x6f\x6e\x73\x18" +
	"\x0a\x20\x01\x28\x08\x52\x1e\x61\x6c\x6c\x6f\x77\x50\x72\x69\x76" +
	"\x61\x74\x65\x4e\x65\x74\x77\x6f\x72\x6b\x43\x6f\x6e\x6e\x65\x63" +
	"\x74\x69\x6f\x6e\x73\x12\x46\x0a\x20\x69\x63\x6d\x70\x5f\x72\x65" +
	"\x63\x76\x5f\x6d\x65\x73\x73\x61\x67\x65\x5f\x71\x75\x65\x75\x65" +
	"\x5f\x63\x61\x70\x61\x63\x69\x74\x79\x18\x0b\x20\x01\x28\x0d\x52" +
	"\x1c\x69\x63\x6d\x70\x52\x65\x63\x76\x4d\x65\x73\x73\x61\x67\x65" +
	"\x51\x75\x65\x75\x65\x43\x61\x70\x61\x63\x69\x74\x79\x12\x3b\x0a" +
	"\x1a\x74\x6c\x73\x5f\x68\x61\x6e\x64\x73\x68\x61\x6b\x65\x5f\x74" +
	"\x69\x6d\x65\x6f\x75\x74\x5f\x73\x65\x63\x73\x18\x0c\x20\x01\x28" +
	"\x0d\x52\x17\x74\x6c\x73\x48\x61\x6e\x64\x73\x68\x61\x6b\x65\x54" +
	"\x69\x6d\x65\x6f\x75\x74\x53\x65\x63\x73\x12\x3f\x0a\x1c\x63\x6c" +
	"\x69\x65\x6e\x74\x5f\x6c\x69\x73\x74\x65\x6e\x65\x72\x5f\x74\x69" +
	"\x6d\x65\x6f\x75\x74\x5f\x73\x65\x63\x73\x18\x0d\x20\x01\x28\x0d" +
	"\x52\x19\x63\x6c\x69\x65\x6e\x74\x4c\x69\x73\x74\x65\x6e\x65\x72" +
	"\x54\x69\x6d\x65\x6f\x75\x74\x53\x65\x63\x73\x12\x51\x0a\x25\x63" +
	"\x6f\x6e\x6e\x65\x63\x74\x69\x6f\x6e\x5f\x65\x73\x74\x61\x62\x6c" +
	"\x69\x73\x68\x6d\x65\x6e\x74\x5f\x74\x69\x6d\x65\x6f\x75\x74\x5f" +
	"\x73\x65\x63\x73\x18\x0e\x20\x01\x28\x0d\x52\x22\x63\x6f\x6e\x6e" +
	"\x65\x63\x74\x69\x6f\x6e\x45\x73\x74\x61\x62\x6c\x69\x73\x68\x6d" +
	"\x65\x6e\x74\x54\x69\x6d\x65\x6f\x75\x74\x53\x65\x63\x73\x12\x3f" +
	"\x0a\x1c\x74\x63\x70\x5f\x63\x6f\x6e\x6e\x65\x63\x74\x69\x6f\x6e" +
	"\x73\x5f\x74\x69\x6d\x65\x6f\x75\x74\x5f\x73\x65\x63\x73\x18\x0f" +
	"\x20\x01\x28\x0d\x52\x19\x74\x63\x70\x43\x6f\x6e\x6e\x65\x63\x74" +
	"\x69\x6f\x6e\x73\x54\x69\x6d\x65\x6f\x75\x74\x53\x65\x63\x73\x12" +
	"\x3f\x0a\x1c\x75\x64\x70\x5f\x63\x6f\x6e\x6e\x65\x63\x74\x69\x6f" +
	"\x6e\x73\x5f\x74\x69\x6d\x65\x6f\x75\x74\x5f\x73\x65\x63\x73\x18" +
	"\x10\x20\x01\x28\x0d\x52\x19\x75\x64\x70\x43\x6f\x6e\x6e\x65\x63" +
	"\x74\x69\x6f\x6e\x73\x54\x69\x6d\x65\x6f\x75\x74\x53\x65\x63\x73" +
	"\x12\x49\x0a\x22\x64\x65\x66\x61\x75\x6c\x74\x5f\x6d\x61\x78\x5f" +
	"\x68\x74\x74\x70\x32\x5f\x63\x6f\x6e\x6e\x73\x5f\x70\x65\x72\x5f" +
	"\x63\x6c\x69\x65\x6e\x74\x18\x11\x20\x01\x28\x0d\x52\x1d\x64\x65" +
	"\x66\x61\x75\x6c\x74\x4d\x61\x78\x48\x74\x74\x70\x32\x43\x6f\x6e" +
	"\x6e\x73\x50\x65\x72\x43\x6c\x69\x65\x6e\x74\x12\x49\x0a\x22\x64" +
	"\x65\x66\x61\x75\x6c\x74\x5f\x6d\x61\x78\x5f\x68\x74\x74\x70\x33" +
	"\x5f\x63\x6f\x6e\x6e\x73\x5f\x70\x65\x72\x5f\x63\x6c\x69\x65\x6e" +
	"\x74\x18\x12\x20\x01\x28\x0d\x52\x1d\x64\x65\x66\x61\x75\x6c\x74" +
	"\x4d\x61\x78\x48\x74\x74\x70\x33\x43\x6f\x6e\x6e\x73\x50\x65\x72" +
	"\x43\x6c\x69\x65\x6e\x74\x2a\x33\x0a\x11\x54\x72\x61\x6e\x73\x70" +
	"\x6f\x72\x74\x50\x72\x6f\x74\x6f\x63\x6f\x6c\x12\x09\x0a\x05\x48" +
	"\x54\x54\x50\x32\x10\x00\x12\x09\x0a\x05\x48\x54\x54\x50\x33\x10" +
	"\x01\x12\x08\x0a\x04\x41\x55\x54\x4f\x10\x02\x2a\x8f\x01\x0a\x17" +
	"\x50\x6f\x73\x74\x51\x75\x61\x6e\x74\x75\x6d\x47\x72\x6f\x75\x70" +
	"\x53\x65\x74\x74\x69\x6e\x67\x12\x23\x0a\x1f\x50\x4f\x53\x54\x5f" +
	"\x51\x55\x41\x4e\x54\x55\x4d\x5f\x47\x52\x4f\x55\x50\x5f\x53\x45" +
	"\x54\x54\x49\x4e\x47\x5f\x41\x55\x54\x4f\x10\x00\x12\x27\x0a\x23" +
	"\x50\x4f\x53\x54\x5f\x51\x55\x41\x4e\x54\x55\x4d\x5f\x47\x52\x4f" +
	"\x55\x50\x5f\x53\x45\x54\x54\x49\x4e\x47\x5f\x44\x49\x53\x41\x42" +
	"\x4c\x45\x44\x10\x01\x12\x26\x0a\x22\x50\x4f\x53\x54\x5f\x51\x55" +
	"\x41\x4e\x54\x55\x4d\x5f\x47\x52\x4f\x55\x50\x5f\x53\x45\x54\x54" +
	"\x49\x4e\x47\x5f\x45\x4e\x41\x42\x4c\x45\x44\x10\x02\x42\x64\x0a" +
	"\x1a\x63\x6f\x6d\x2e\x78\x72\x61\x79\x2e\x70\x72\x6f\x78\x79\x2e" +
	"\x74\x72\x75\x73\x74\x74\x75\x6e\x6e\x65\x6c\x50\x01\x5a\x2b\x67" +
	"\x69\x74\x68\x75\x62\x2e\x63\x6f\x6d\x2f\x78\x74\x6c\x73\x2f\x78" +
	"\x72\x61\x79\x2d\x63\x6f\x72\x65\x2f\x70\x72\x6f\x78\x79\x2f\x74" +
	"\x72\x75\x73\x74\x74\x75\x6e\x6e\x65\x6c\xaa\x02\x16\x58\x72\x61" +
	"\x79\x2e\x50\x72\x6f\x78\x79\x2e\x54\x72\x75\x73\x74\x54\x75\x6e" +
	"\x6e\x65\x6c\x62\x06\x70\x72\x6f\x74\x6f\x33"

var (
	file_proxy_trusttunnel_config_proto_rawDescOnce sync.Once
	file_proxy_trusttunnel_config_proto_rawDescData []byte
)

func file_proxy_trusttunnel_config_proto_rawDescGZIP() []byte {
	file_proxy_trusttunnel_config_proto_rawDescOnce.Do(func() {
		file_proxy_trusttunnel_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_trusttunnel_config_proto_rawDesc), len(file_proxy_trusttunnel_config_proto_rawDesc)))
	})
	return file_proxy_trusttunnel_config_proto_rawDescData
}

var file_proxy_trusttunnel_config_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proxy_trusttunnel_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proxy_trusttunnel_config_proto_goTypes = []any{
	(TransportProtocol)(0),          // 0: xray.proxy.trusttunnel.TransportProtocol
	(PostQuantumGroupSetting)(0),    // 1: xray.proxy.trusttunnel.PostQuantumGroupSetting
	(*Account)(nil),                 // 2: xray.proxy.trusttunnel.Account
	(*Rule)(nil),                    // 3: xray.proxy.trusttunnel.Rule
	(*ServerHost)(nil),              // 4: xray.proxy.trusttunnel.ServerHost
	(*ClientConfig)(nil),            // 5: xray.proxy.trusttunnel.ClientConfig
	(*ServerConfig)(nil),            // 6: xray.proxy.trusttunnel.ServerConfig
	(*protocol.ServerEndpoint)(nil), // 7: xray.common.protocol.ServerEndpoint
	(*protocol.User)(nil),           // 8: xray.common.protocol.User
}
var file_proxy_trusttunnel_config_proto_depIdxs = []int32{
	7, // 0: xray.proxy.trusttunnel.ClientConfig.server:type_name -> xray.common.protocol.ServerEndpoint
	0, // 1: xray.proxy.trusttunnel.ClientConfig.transport:type_name -> xray.proxy.trusttunnel.TransportProtocol
	1, // 2: xray.proxy.trusttunnel.ClientConfig.post_quantum_group_enabled:type_name -> xray.proxy.trusttunnel.PostQuantumGroupSetting
	7, // 3: xray.proxy.trusttunnel.ClientConfig.servers:type_name -> xray.common.protocol.ServerEndpoint
	8, // 4: xray.proxy.trusttunnel.ServerConfig.users:type_name -> xray.common.protocol.User
	4, // 5: xray.proxy.trusttunnel.ServerConfig.hosts:type_name -> xray.proxy.trusttunnel.ServerHost
	0, // 6: xray.proxy.trusttunnel.ServerConfig.transports:type_name -> xray.proxy.trusttunnel.TransportProtocol
	3, // 7: xray.proxy.trusttunnel.ServerConfig.rules:type_name -> xray.proxy.trusttunnel.Rule
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proxy_trusttunnel_config_proto_init() }
func file_proxy_trusttunnel_config_proto_init() {
	if File_proxy_trusttunnel_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_trusttunnel_config_proto_rawDesc), len(file_proxy_trusttunnel_config_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_trusttunnel_config_proto_goTypes,
		DependencyIndexes: file_proxy_trusttunnel_config_proto_depIdxs,
		EnumInfos:         file_proxy_trusttunnel_config_proto_enumTypes,
		MessageInfos:      file_proxy_trusttunnel_config_proto_msgTypes,
	}.Build()
	File_proxy_trusttunnel_config_proto = out.File
	file_proxy_trusttunnel_config_proto_goTypes = nil
	file_proxy_trusttunnel_config_proto_depIdxs = nil
}
