// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proxy/trusttunnel/config.proto

package trusttunnel

import (
	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransportProtocol int32

const (
	TransportProtocol_HTTP2 TransportProtocol = 0
	TransportProtocol_HTTP3 TransportProtocol = 1
)

// Enum value maps for TransportProtocol.
var (
	TransportProtocol_name = map[int32]string{
		0: "HTTP2",
		1: "HTTP3",
	}
	TransportProtocol_value = map[string]int32{
		"HTTP2": 0,
		"HTTP3": 1,
	}
)

func (x TransportProtocol) Enum() *TransportProtocol {
	p := new(TransportProtocol)
	*p = x
	return p
}

func (x TransportProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_trusttunnel_config_proto_enumTypes[0].Descriptor()
}

func (TransportProtocol) Type() protoreflect.EnumType {
	return &file_proxy_trusttunnel_config_proto_enumTypes[0]
}

func (x TransportProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportProtocol.Descriptor instead.
func (TransportProtocol) EnumDescriptor() ([]byte, []int) {
	return file_proxy_trusttunnel_config_proto_rawDescGZIP(), []int{0}
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_trusttunnel_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	ClientRandom  string                 `protobuf:"bytes,2,opt,name=client_random,json=clientRandom,proto3" json:"client_random,omitempty"`
	Allow         bool                   `protobuf:"varint,3,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_proxy_trusttunnel_config_proto_rawDescGZIP(), []int{1}
}

func (x *Rule) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *Rule) GetClientRandom() string {
	if x != nil {
		return x.ClientRandom
	}
	return ""
}

func (x *Rule) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

type ServerHost struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Hostname        string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CertificatePath string                 `protobuf:"bytes,2,opt,name=certificate_path,json=certificatePath,proto3" json:"certificate_path,omitempty"`
	KeyPath         string                 `protobuf:"bytes,3,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerHost) Reset() {
	*x = ServerHost{}
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHost) ProtoMessage() {}

func (x *ServerHost) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHost.ProtoReflect.Descriptor instead.
func (*ServerHost) Descriptor() ([]byte, []int) {
	return file_proxy_trusttunnel_config_proto_rawDescGZIP(), []int{2}
}

func (x *ServerHost) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ServerHost) GetCertificatePath() string {
	if x != nil {
		return x.CertificatePath
	}
	return ""
}

func (x *ServerHost) GetKeyPath() string {
	if x != nil {
		return x.KeyPath
	}
	return ""
}

type ClientConfig struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	Server           *protocol.ServerEndpoint `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Hostname         string                   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Transport        TransportProtocol        `protobuf:"varint,3,opt,name=transport,proto3,enum=xray.proxy.trusttunnel.TransportProtocol" json:"transport,omitempty"`
	HasIpv6          bool                     `protobuf:"varint,4,opt,name=has_ipv6,json=hasIpv6,proto3" json:"has_ipv6,omitempty"`
	SkipVerification bool                     `protobuf:"varint,5,opt,name=skip_verification,json=skipVerification,proto3" json:"skip_verification,omitempty"`
	CertificatePem   string                   `protobuf:"bytes,6,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	ClientRandom     string                   `protobuf:"bytes,7,opt,name=client_random,json=clientRandom,proto3" json:"client_random,omitempty"`
	AntiDpi          bool                     `protobuf:"varint,8,opt,name=anti_dpi,json=antiDpi,proto3" json:"anti_dpi,omitempty"`
	EnableUdp        bool                     `protobuf:"varint,9,opt,name=enable_udp,json=enableUdp,proto3" json:"enable_udp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_proxy_trusttunnel_config_proto_rawDescGZIP(), []int{3}
}

func (x *ClientConfig) GetServer() *protocol.ServerEndpoint {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ClientConfig) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ClientConfig) GetTransport() TransportProtocol {
	if x != nil {
		return x.Transport
	}
	return TransportProtocol_HTTP2
}

func (x *ClientConfig) GetHasIpv6() bool {
	if x != nil {
		return x.HasIpv6
	}
	return false
}

func (x *ClientConfig) GetSkipVerification() bool {
	if x != nil {
		return x.SkipVerification
	}
	return false
}

func (x *ClientConfig) GetCertificatePem() string {
	if x != nil {
		return x.CertificatePem
	}
	return ""
}

func (x *ClientConfig) GetClientRandom() string {
	if x != nil {
		return x.ClientRandom
	}
	return ""
}

func (x *ClientConfig) GetAntiDpi() bool {
	if x != nil {
		return x.AntiDpi
	}
	return false
}

func (x *ClientConfig) GetEnableUdp() bool {
	if x != nil {
		return x.EnableUdp
	}
	return false
}

type ServerConfig struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Users                          []*protocol.User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Hosts                          []*ServerHost          `protobuf:"bytes,2,rep,name=hosts,proto3" json:"hosts,omitempty"`
	Transports                     []TransportProtocol    `protobuf:"varint,3,rep,packed,name=transports,proto3,enum=xray.proxy.trusttunnel.TransportProtocol" json:"transports,omitempty"`
	Rules                          []*Rule                `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	Ipv6Available                  bool                   `protobuf:"varint,5,opt,name=ipv6_available,json=ipv6Available,proto3" json:"ipv6_available,omitempty"`
	AuthFailureStatusCode          uint32                 `protobuf:"varint,6,opt,name=auth_failure_status_code,json=authFailureStatusCode,proto3" json:"auth_failure_status_code,omitempty"`
	EnableUdp                      bool                   `protobuf:"varint,7,opt,name=enable_udp,json=enableUdp,proto3" json:"enable_udp,omitempty"`
	IcmpInterfaceName              string                 `protobuf:"bytes,8,opt,name=icmp_interface_name,json=icmpInterfaceName,proto3" json:"icmp_interface_name,omitempty"`
	IcmpRequestTimeoutSecs         uint32                 `protobuf:"varint,9,opt,name=icmp_request_timeout_secs,json=icmpRequestTimeoutSecs,proto3" json:"icmp_request_timeout_secs,omitempty"`
	AllowPrivateNetworkConnections bool                   `protobuf:"varint,10,opt,name=allow_private_network_connections,json=allowPrivateNetworkConnections,proto3" json:"allow_private_network_connections,omitempty"`
	IcmpRecvMessageQueueCapacity   uint32                 `protobuf:"varint,11,opt,name=icmp_recv_message_queue_capacity,json=icmpRecvMessageQueueCapacity,proto3" json:"icmp_recv_message_queue_capacity,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_trusttunnel_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_trusttunnel_config_proto_rawDescGZIP(), []int{4}
}

func (x *ServerConfig) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ServerConfig) GetHosts() []*ServerHost {
	if x != nil {
		return x.Hosts
	}
	return nil
}

func (x *ServerConfig) GetTransports() []TransportProtocol {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *ServerConfig) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ServerConfig) GetIpv6Available() bool {
	if x != nil {
		return x.Ipv6Available
	}
	return false
}

func (x *ServerConfig) GetAuthFailureStatusCode() uint32 {
	if x != nil {
		return x.AuthFailureStatusCode
	}
	return 0
}

func (x *ServerConfig) GetEnableUdp() bool {
	if x != nil {
		return x.EnableUdp
	}
	return false
}

func (x *ServerConfig) GetIcmpInterfaceName() string {
	if x != nil {
		return x.IcmpInterfaceName
	}
	return ""
}

func (x *ServerConfig) GetIcmpRequestTimeoutSecs() uint32 {
	if x != nil {
		return x.IcmpRequestTimeoutSecs
	}
	return 0
}

func (x *ServerConfig) GetAllowPrivateNetworkConnections() bool {
	if x != nil {
		return x.AllowPrivateNetworkConnections
	}
	return false
}

func (x *ServerConfig) GetIcmpRecvMessageQueueCapacity() uint32 {
	if x != nil {
		return x.IcmpRecvMessageQueueCapacity
	}
	return 0
}

var File_proxy_trusttunnel_config_proto protoreflect.FileDescriptor

const file_proxy_trusttunnel_config_proto_rawDesc = "" +
	"\n" +
	"\x1eproxy/trusttunnel/config.proto\x12\x16xray.proxy.trusttunnel\x1a\x1acommon/protocol/user.proto\x1a!common/protocol/server_spec.proto\"A\n" +
	"\aAccount\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"U\n" +
	"\x04Rule\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12#\n" +
	"\rclient_random\x18\x02 \x01(\tR\fclientRandom\x12\x14\n" +
	"\x05allow\x18\x03 \x01(\bR\x05allow\"n\n" +
	"\n" +
	"ServerHost\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12)\n" +
	"\x10certificate_path\x18\x02 \x01(\tR\x0fcertificatePath\x12\x19\n" +
	"\bkey_path\x18\x03 \x01(\tR\akeyPath\"\x81\x03\n" +
	"\fClientConfig\x12<\n" +
	"\x06server\x18\x01 \x01(\v2$.xray.common.protocol.ServerEndpointR\x06server\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12G\n" +
	"\ttransport\x18\x03 \x01(\x0e2).xray.proxy.trusttunnel.TransportProtocolR\ttransport\x12\x19\n" +
	"\bhas_ipv6\x18\x04 \x01(\bR\ahasIpv6\x12+\n" +
	"\x11skip_verification\x18\x05 \x01(\bR\x10skipVerification\x12'\n" +
	"\x0fcertificate_pem\x18\x06 \x01(\tR\x0ecertificatePem\x12#\n" +
	"\rclient_random\x18\a \x01(\tR\fclientRandom\x12\x19\n" +
	"\banti_dpi\x18\b \x01(\bR\aantiDpi\x12\x1d\n" +
	"\n" +
	"enable_udp\x18\t \x01(\bR\tenableUdp\"\xf6\x04\n" +
	"\fServerConfig\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.xray.common.protocol.UserR\x05users\x128\n" +
	"\x05hosts\x18\x02 \x03(\v2\".xray.proxy.trusttunnel.ServerHostR\x05hosts\x12I\n" +
	"\n" +
	"transports\x18\x03 \x03(\x0e2).xray.proxy.trusttunnel.TransportProtocolR\n" +
	"transports\x122\n" +
	"\x05rules\x18\x04 \x03(\v2\x1c.xray.proxy.trusttunnel.RuleR\x05rules\x12%\n" +
	"\x0eipv6_available\x18\x05 \x01(\bR\ripv6Available\x127\n" +
	"\x18auth_failure_status_code\x18\x06 \x01(\rR\x15authFailureStatusCode\x12\x1d\n" +
	"\n" +
	"enable_udp\x18\a \x01(\bR\tenableUdp\x12.\n" +
	"\x13icmp_interface_name\x18\b \x01(\tR\x11icmpInterfaceName\x129\n" +
	"\x19icmp_request_timeout_secs\x18\t \x01(\rR\x16icmpRequestTimeoutSecs\x12I\n" +
	"!allow_private_network_connections\x18\n" +
	" \x01(\bR\x1eallowPrivateNetworkConnections\x12F\n" +
	" icmp_recv_message_queue_capacity\x18\v \x01(\rR\x1cicmpRecvMessageQueueCapacity*)\n" +
	"\x11TransportProtocol\x12\t\n" +
	"\x05HTTP2\x10\x00\x12\t\n" +
	"\x05HTTP3\x10\x01Bd\n" +
	"\x1acom.xray.proxy.trusttunnelP\x01Z+github.com/xtls/xray-core/proxy/trusttunnel\xaa\x02\x16Xray.Proxy.TrustTunnelb\x06proto3"

var (
	file_proxy_trusttunnel_config_proto_rawDescOnce sync.Once
	file_proxy_trusttunnel_config_proto_rawDescData []byte
)

func file_proxy_trusttunnel_config_proto_rawDescGZIP() []byte {
	file_proxy_trusttunnel_config_proto_rawDescOnce.Do(func() {
		file_proxy_trusttunnel_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_trusttunnel_config_proto_rawDesc), len(file_proxy_trusttunnel_config_proto_rawDesc)))
	})
	return file_proxy_trusttunnel_config_proto_rawDescData
}

var file_proxy_trusttunnel_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proxy_trusttunnel_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proxy_trusttunnel_config_proto_goTypes = []any{
	(TransportProtocol)(0),          // 0: xray.proxy.trusttunnel.TransportProtocol
	(*Account)(nil),                 // 1: xray.proxy.trusttunnel.Account
	(*Rule)(nil),                    // 2: xray.proxy.trusttunnel.Rule
	(*ServerHost)(nil),              // 3: xray.proxy.trusttunnel.ServerHost
	(*ClientConfig)(nil),            // 4: xray.proxy.trusttunnel.ClientConfig
	(*ServerConfig)(nil),            // 5: xray.proxy.trusttunnel.ServerConfig
	(*protocol.ServerEndpoint)(nil), // 6: xray.common.protocol.ServerEndpoint
	(*protocol.User)(nil),           // 7: xray.common.protocol.User
}
var file_proxy_trusttunnel_config_proto_depIdxs = []int32{
	6, // 0: xray.proxy.trusttunnel.ClientConfig.server:type_name -> xray.common.protocol.ServerEndpoint
	0, // 1: xray.proxy.trusttunnel.ClientConfig.transport:type_name -> xray.proxy.trusttunnel.TransportProtocol
	7, // 2: xray.proxy.trusttunnel.ServerConfig.users:type_name -> xray.common.protocol.User
	3, // 3: xray.proxy.trusttunnel.ServerConfig.hosts:type_name -> xray.proxy.trusttunnel.ServerHost
	0, // 4: xray.proxy.trusttunnel.ServerConfig.transports:type_name -> xray.proxy.trusttunnel.TransportProtocol
	2, // 5: xray.proxy.trusttunnel.ServerConfig.rules:type_name -> xray.proxy.trusttunnel.Rule
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proxy_trusttunnel_config_proto_init() }
func file_proxy_trusttunnel_config_proto_init() {
	if File_proxy_trusttunnel_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_trusttunnel_config_proto_rawDesc), len(file_proxy_trusttunnel_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_trusttunnel_config_proto_goTypes,
		DependencyIndexes: file_proxy_trusttunnel_config_proto_depIdxs,
		EnumInfos:         file_proxy_trusttunnel_config_proto_enumTypes,
		MessageInfos:      file_proxy_trusttunnel_config_proto_msgTypes,
	}.Build()
	File_proxy_trusttunnel_config_proto = out.File
	file_proxy_trusttunnel_config_proto_goTypes = nil
	file_proxy_trusttunnel_config_proto_depIdxs = nil
}
